import { craft, cron, mail } from "@routecraft/routecraft";
import { env } from "../env.js";
import { listTickets } from "../lib/clients/planka.js";
import { findKnowledgeFiles } from "../lib/clients/s3.js";

/**
 * Monday-morning board digest. Deterministic: no agent, no LLM.
 *
 * This is the harness's proof that the platform hosts ordinary automation
 * as well as agents. Counting cards and listing recently-changed files needs
 * no judgement, so paying for a model here would be slower, costlier, and
 * less predictable than the twenty lines below.
 *
 * The heartbeat route next door is the agentic counterpart: same `cron()`
 * source, but it hands the moment to Aria because the task genuinely needs
 * judgement.
 */
export default craft()
  .id("weekly-digest")
  .from(cron("0 8 * * MON"))
  .transform(async () => {
    const [tickets, knowledge] = await Promise.all([
      listTickets(),
      findKnowledgeFiles({ limit: 50 }),
    ]);

    const byStatus = new Map<string, number>();
    for (const ticket of tickets) {
      byStatus.set(ticket.status, (byStatus.get(ticket.status) ?? 0) + 1);
    }

    const weekAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const recent = tickets.filter(
      (t) => Date.parse(t.createdAt) >= weekAgo,
    );

    const counts = [...byStatus.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([status, count]) => `  ${status}: ${count}`)
      .join("\n");

    const newCards = recent.length
      ? recent.map((t) => `  - ${t.title} (${t.status})\n    ${t.url}`).join("\n")
      : "  (none)";

    return {
      to: env.DIGEST_RECIPIENT,
      subject: `Board digest: ${tickets.length} open items`,
      text: [
        "Weekly board digest",
        "",
        `Cards by list (${tickets.length} total):`,
        counts || "  (board is empty)",
        "",
        `Created in the last 7 days (${recent.length}):`,
        newCards,
        "",
        `Knowledge base: ${knowledge.length} documents.`,
        "",
        "Generated by the Craft Harness digest route. No agent was involved.",
      ].join("\n"),
    };
  })
  .to(mail({ account: "default" }));
