import { craft, cron, direct, mail, only } from "@routecraft/routecraft";
import { env } from "../env.js";
import { scheduled } from "../lib/identity.js";
import type { TicketSummary } from "../lib/planka.js";

/**
 * Monday-morning board digest. Deterministic: no agent, no LLM.
 *
 * This is the harness's proof that the platform hosts ordinary automation
 * as well as agents. Counting cards and listing recently-changed files needs
 * no judgement, so paying for a model here would be slower, costlier, and
 * less predictable than the twenty lines below.
 *
 * The heartbeat route next door is the agentic counterpart: same `cron()`
 * source, but it hands the moment to Aria because the task genuinely needs
 * judgement.
 */
export default craft()
  .id("weekly-digest")
  .from(cron("0 8 * * MON"))
  // eslint-disable-next-line @routecraft/routecraft/restrict-principal-minting -- an internal cron trigger, the only sanctioned source of standing authority. Nothing inbound can reach this line
  .authenticate(() => scheduled("weekly-digest"))
  // cron delivers an empty body. This one doubles as the request body for the
  // enrichment below, which is why it carries a limit.
  .transform(() => ({ limit: 50 }))
  // Both figures come from the same capabilities the agent uses, so the digest
  // and the agent can never disagree about what is on the board or on file.
  .enrich(
    direct<unknown, { results: unknown[] }>("knowledge-find"),
    only((r: { results: unknown[] }) => r.results.length, "documents"),
  )
  .enrich(
    direct<unknown, { tickets: TicketSummary[] }>("list-tickets"),
    only((r: { tickets: TicketSummary[] }) => r.tickets, "tickets"),
  )
  .transform((body) => {
    const tickets = body.tickets;

    const byStatus = new Map<string, number>();
    for (const ticket of tickets) {
      byStatus.set(ticket.status, (byStatus.get(ticket.status) ?? 0) + 1);
    }

    const weekAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const recent = tickets.filter((t) => Date.parse(t.createdAt) >= weekAgo);

    const counts = [...byStatus.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([status, count]) => `  ${status}: ${count}`)
      .join("\n");

    const newCards = recent.length
      ? recent
          .map((t) => `  - ${t.title} (${t.status})\n    ${t.url}`)
          .join("\n")
      : "  (none)";

    return {
      to: env.DIGEST_RECIPIENT,
      subject: `Board digest: ${tickets.length} open items`,
      text: [
        "Weekly board digest",
        "",
        `Cards by list (${tickets.length} total):`,
        counts || "  (board is empty)",
        "",
        `Created in the last 7 days (${recent.length}):`,
        newCards,
        "",
        `Knowledge base: ${body.documents} documents.`,
        "",
        "Generated by the Craft Harness digest route. No agent was involved.",
      ].join("\n"),
    };
  })
  .to(mail({ account: "default" }));
